### ISSUE TITLE
Advanced Reachability

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#103]
Add Reachability to 
1. Followers and Following (UsersVC.swift)
2. Liked and Post History (PlayerTableVC.swift - likely also involves removing this code out of Feed)
3. People and Song Search (SearchVC.swift)
Issue with this being simple stems from SearchBar
@natashaarmbrust is our "resident expert" on how this works.

**Comment by lucasderraugh** [comment]
Closed in d0c3c81
