### ISSUE TITLE
Implement Friend Suggestions

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#105]
@ifilonenko Implemented Friend Suggestion on the backend. There should be a new tab on the side for user suggestion. This tab should return a list of user cells (just like followers or following or people search). I believe @ifilonenko paginated this return so we should should have a load more button at the bottom. At the moment a user would follow other users by click on a user cell, going to their profile view and clicking follow. We might revisit later and add a follow button to the side in this view as you should only be returned users you are not currently following.

Load more behavior:
1. Simply append another page (5) of users to bottom of the view.
2. If you click in and follow a user, it should remove them from the suggestion list. (Careful to not remove if you follow and then unfollow and then go back to the list)

**Comment by lucasderraugh** [comment]
Closed in #110
