### ISSUE TITLE
FeedCell Scrolling Text Issues

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#12]
1. Cell Name overlaps with time posted.
2. Text Scrolling speed should be slower - change from 100 to 75
3. Names and Titles both Scroll when only one needs to.
4. Songs that we played in preview keep scrolling after starting to play another song.

**Comment by say25** [comment]
Completed: 2. Text Scrolling speed should be slower - change from 100 to 75

**Comment by mrkbryn** [comment]
Completed: 1

**Comment by say25** [comment]
Name is a fixed size, should be variable
