### ISSUE TITLE
Previously playing cell doesn't stop "animating" when another cell is selected

### ISSUE THREAD

**Issue by loganallen** [cuappdev/icefishing#120]
This issue only occurs when a cell starts playing from continuous playing and another cell is selected to play. The audio transfers, but the old animation (spinning logo/red label) does not.

(ie. song 1 is selected, then after 30 seconds song 2 becomes selected and starts playing audio, and then song 3 is selected. Song 3 starts animating and playing, but song 2 only stops playing audio)

**Comment by ChenJesse** [comment]
Is this bug on master or on your expand branch? I can't replicate this bug on master but I can on your branch

**Comment by loganallen** [comment]
Oh you're right okay I'll investigate
