### ISSUE TITLE
Liked posts not in correct order in "Liked" Tab

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#126]
Should be in chronological order. Either backend needs to sort before sending to us, or send us the date that we liked each post so we can sort it.

**Comment by jk2227** [comment]
https://github.com/cuappdev/tempo-backend/commit/0e5557b51f63cc4323023b40a7a19518801f4ed3

^ seems like that's all I have to do? Should test it out though

**Comment by dennisfedorko** [comment]
Looks like this is working correctly so I'm closing this issue
