### ISSUE TITLE
Impose username/name character limit

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#127]
Currently if the username/name is too long it conflicts with the cell's buttons in the people tab. We should cap the length of these or somehow cut off the names so it's not too long

**Comment by dennisfedorko** [comment]
Implemented but needs to be tested

**Comment by dennisfedorko** [comment]
We also need to shorten how names appear, if someone's first/last name is too long we should display it with a short form: Adam Levine West -> Adam West,   John Applebottomjeans -> John A.

**Comment by keivanshahida** [comment]
Make last name an initial if too long.
