### ISSUE TITLE
Profile View - Scrolling

### ISSUE THREAD

**Issue by aelshaer** [cuappdev/icefishing#137]
When scrolling up, the top half of the screen should collapse so that more of post history is visible

**Comment by dennisfedorko** [comment]
Not currently feasible with the XIB setup, will have to wait until we refactor post-release

**Comment by tz226** [comment]
(delayed response but) wait then the page is pretty much unusable for iPhone 5s. I can barely see one row of the calendar

**Comment by dennisfedorko** [comment]
we'll have to address that at a later period of time

**Comment by say25** [comment]
@dennisfedorko fixed no?
