### ISSUE TITLE
Login Username Screen

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#153]
# **TO DO**
- [x] "Username unavailable" message does not update as I change my username.
- [x] If you "ninja" past "log in with facebook screen" after previously logging this screen actually changes you username for the last logged in user
- [x] Animate user photo to change alpha when keyboard opened
- [x] When touching outside of keyboard, keyboard should close
- [x] Add padding to placeholder in uitextfield
- [x] Change text label so that the error messages are not cut off

**Comment by keivanshahida** [comment]
Animate user photo to change alpha when keyboard opened

**Comment by keivanshahida** [comment]
When touching outside of keyboard, keyboard should close

**Comment by keivanshahida** [comment]
change text label so that the error messages are not cut off

**Comment by keivanshahida** [comment]
Add padding to placeholder in uitextfield

**Comment by keivanshahida** [comment]
- [ Animate user photo to change alpha when keyboard opened]

**Comment by keivanshahida** [comment]
- [ ] Animate user photo to change alpha when keyboard opened
- [ ] When touching outside of keyboard, keyboard should close
- [ ] change text label so that the error messages are not cut off
- [ ] Add padding to placeholder in uitextfield
