### ISSUE TITLE
Following/Followers Bugs

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#173]
- [x] Self Follow (is this by design?)
Probably can be solved by retrieving followers and following count on view did appear:
- [x] Go into following, unfollow someone, go back to profile screen following count doesnt update
- [x] Go into followers, follow someone, go back to profile screen followers count doesnt update

**Comment by dennisfedorko** [comment]
What do you mean by self follow?

**Comment by say25** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/7467062/20801887/e93bc016-b7af-11e6-8eef-01c17ef8d004.jpg)

**Comment by dennisfedorko** [comment]
I believe this will be solved with a db wipe

**Comment by say25** [comment]
ok marked that subtask as complete for now. but rest seem valid no?
