### ISSUE TITLE
When logging into Facebook, it says "Facebook wants to open IceFishing"

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/icefishing#189]
and then it somehow goes to the old version of the app? Maybe it's just on my phone

**Comment by say25** [comment]
No this is a legit "bug" Facebook app is still named Icefishing I believe

**Comment by say25** [comment]
But I get tempo on login usually.

**Comment by keivanshahida** [comment]
We scrubbed Icefishing from our FB dev settings a long time ago, I'll keep looking into though.

**Comment by keivanshahida** [comment]
Icefishing has been scrubbed everywhere except for our Spotify redirect URI's in their dev portal.

**Comment by dennisfedorko** [comment]
On this same note, Tempo Web should be renamed to Tempo on the Facebook account

**Comment by keivanshahida** [comment]
Changed from Tempo Web to Tempo
