### ISSUE TITLE
Miscellaneous UI Polishes

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/icefishing#19]
- [x] Change Edit to Edit Username on Profile Screen
- [ ] Make empty state views more inviting
- [x] Get rid of likes in Liked view
- [x] Fix positioning of plus button in Liked View
- [ ] Implement better design for Login Screen
- [ ] Remove Login button and show loading screen after login attempt. Bring back button only on failure.

More to come...

**Comment by natashaarmbrust** [comment]
Plus button in liked view? it isn't there

**Comment by say25** [comment]
Yes. Only when logged into Spotify should it appear

**Comment by natashaarmbrust** [comment]
Yes it is not?

**Comment by say25** [comment]
You'd have to check. It should only show up after logging into Spotify.

**Comment by natashaarmbrust** [comment]
Add spotify view enhancement .. CHECK

**Comment by anniexcheng** [comment]
UI Issues can be addressed when new designs are in. Closing this for now.
