### ISSUE TITLE
Song doesn't show as saved

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/icefishing#190]
1. Add a song to your Spotify in Liked view
2. Log out of Spotify
3. Log back into Spotify
4. Go back to Liked View, and song isn't marked as added

**Comment by dennisfedorko** [comment]
To implement this we would have to get the users saved Spotify songs from the Spotify api each time they open the app and update the cells accordingly.

The adding/removing behavior still works correctly, the song is added if you press + and removed if you undo it, it's just not as user friendly as it could be.

We can save this for post-release

**Comment by ChenJesse** [comment]
Right now, the tracks are saved in UserDefaults.
