### ISSUE TITLE
Compatibility on different iPhone sizes

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/icefishing#196]

**Comment by keivanshahida** [comment]
- [x] iPhone 5/S/SE
- [x] iPhone 6/S
- [x] iPhone 6/S Plus
- [x] iPhone 7
- [x] iPhone 7 Plus

**Comment by keivanshahida** [comment]
**Current Compatibility Issues:**
**_iPhone 5_**

- [x] When the player is expanded, either change "Open in Spotify" to just "Open" or "Save to Spotify" to just "Save".
- [x] On profile, hipster cred is being cut off.
