### ISSUE TITLE
Expanded player while on Post a Track page

### ISSUE THREAD

**Issue by tz226** [cuappdev/icefishing#197]
When expanding the player while playing a song off on the post a track page, it says that I posted the song when really I haven't yet. 

Should say 'From your search results'. 

![img_8967](https://cloud.githubusercontent.com/assets/7338439/20915344/47380250-bb53-11e6-9e71-46c7db6a56d6.PNG)

**Comment by anniexcheng** [comment]
Addressed in 3dc87f3
