### ISSUE TITLE
Pull refresh on Post History

### ISSUE THREAD

**Issue by tz226** [cuappdev/icefishing#199]
Can we change it so the search bar sticks to the top when refreshing? 
![img_0441](https://cloud.githubusercontent.com/assets/7338439/21037673/b098ccba-bd9d-11e6-9322-da5b58142f49.PNG)

**Comment by say25** [comment]
Think this could go for other sections of the app to like Followers/Following, People & Liked. Believe they all inherit from the same View Controller so should be an easy "win" to get that done across the board.
