### ISSUE TITLE
For names with a space in the middle, the second part gets removed

### ISSUE THREAD

**Issue by tz226** [cuappdev/icefishing#200]
For first names that have a space in the middle (e.g. 'Yeon Soo'), name throughout the app incorrectly appears as just 'Yeon'.

**Comment by say25** [comment]
^ @ChenJesse can this issue be closed?

**Comment by jk2227** [comment]
I updated and my name is shown as Ji Kim; let me check the DB to see if it was the way my name was stored originally...

**Comment by jk2227** [comment]
![image](https://cloud.githubusercontent.com/assets/8561804/21920412/e9e82e8c-d92e-11e6-8ec8-050d88baa71e.png)

Looks like my name is stored as Ji Hun Kim in the DB but it shows up as Ji Kim

![image](https://cloud.githubusercontent.com/assets/8561804/21920439/12f89e2e-d92f-11e6-8f0c-3f511ec13ac5.png)

**Comment by ChenJesse** [comment]
lemme look into it

**Comment by ChenJesse** [comment]
Yea that bug is appearing on the TestFlight version right? It's fixed on the simulator but not on the TestFlight for me, so maybe the TestFlight isn't completely up to date?

**Comment by jk2227** [comment]
Yep on the TestFlight

**Comment by ChenJesse** [comment]
Yea pretty sure it's just TestFlight not being completely up to date, this is my simulator of most recent master branch

![simulator screen shot jan 13 2017 1 41 35 am](https://cloud.githubusercontent.com/assets/11747956/21920792/73c7306a-d931-11e6-9c3a-2afcee9942a6.png)
