### ISSUE TITLE
Tapping on Add to Spotify while not logged in

### ISSUE THREAD

**Issue by tz226** [cuappdev/icefishing#201]
When a user taps on the plus button on the sticky player, it brings them to the settings page. There is no easy way to bring themselves back to the Feed. 

Temporary fix would be to have the navigation on the side show that you are in the settings page. See below, it shows that you are still on Feed. 

But the screen is still slightly confusing since it shows notifications settings as well, I'll look into designing a better screen that makes it clear right away that button is for people connected to spotify. 

![img_0439](https://cloud.githubusercontent.com/assets/7338439/21037722/10d95ebe-bd9e-11e6-84be-0366a0f54ff2.PNG)

**Comment by dennisfedorko** [comment]
Currently as of 0.9 they can press the back arrow in navigation bar to go back to what they were doing

**Comment by ChenJesse** [comment]
Yeah like Dennis said, I addressed this issue so I'm just gonna close it
