### ISSUE TITLE
iPhone 5 screen fixes

### ISSUE THREAD

**Issue by tz226** [cuappdev/icefishing#219]
Due to iPhone 5's smaller screen size, some adjustments need to be made...here are the top two. Probably more needed later. 

1. EXPANDED PLAYER
When the player is expanded, either change "Open in Spotify" to just "Open" or "Save to Spotify" to just "Save". 

2. PEOPLE CELLS
In people cells, large portions of users' names gets cut off. Change FOLLOW button to be smaller and the text of someone's name to be smaller. See Zeplin for People page ([https://zpl.io/2cip4y](https://zpl.io/2cip4y)) and Suggested People to Follow ( [https://zpl.io/Zrzhh8](https://zpl.io/Zrzhh8)). 

EDIT: Change the SHARE button to match this button size.

**Comment by tz226** [comment]
oh and on profile, hipster cred is being cut off. :'( maybe decrease all (hipster cred, followers, following) a font size lol for a quick fix

**Comment by jk2227** [comment]
+1 shows up as HIPSTER CR...

**Comment by tz226** [comment]
omg another iphone 5 user :O

**Comment by keivanshahida** [comment]
"cant share a song on iphone 5" - Dennis
