### ISSUE TITLE
Make it easier to post a song

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#223]
Make it more obvious how to post a song than just having a + button

**Comment by jk2227** [comment]
Yeah maybe having a tutorial animation the first time users download the app may be helpful? I have seen this in some apps before...

**Comment by dennisfedorko** [comment]
I was thinking add something to the feed such as that "what's on your mind" block in the Facebook app.

**Comment by loganallen** [comment]
The restructuring of this ties into the creation of the notification center
