### ISSUE TITLE
Add button turned into X? 

### ISSUE THREAD

**Issue by jk2227** [cuappdev/icefishing#226]
![image](https://cloud.githubusercontent.com/assets/8561804/22424562/ffe017ec-e6c4-11e6-8271-46d2c998501c.png)

Pressing X seems to have done nothing after this mysterious transformation...

**Comment by keivanshahida** [comment]
I was able to replicate this by closing the app, opening the "post" force touch option, leaving the app (without quitting out), and then using the "post" force touch option again.
