### ISSUE TITLE
Reset hipster score penalty at midnight

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#234]
users should be able to post 5 new songs every day without facing a hipster score penalty, and this should reset at midnight. It's hard to keep track of how many songs you posted in the past 24 hrs.

When a user posts it's currently:
hipsterScore += (4 - numberOfPostsInPast24Hrs)

When a user posts it should be:
hipsterScore += (5 - numberOfPostsToday)

**Comment by jk2227** [comment]
https://github.com/cuappdev/tempo-backend/commit/ace6eb79363ddfc11d16a1bd146b541300062f78 

https://github.com/cuappdev/tempo-backend/commit/574eacc878eabc911d8331c4692f3f1035357d0f

Resolved
