### ISSUE TITLE
Make banner for in-app notifications

### ISSUE THREAD

**Issue by loganallen** [cuappdev/icefishing#240]
Also make external notification actions bring you to the correct view within the app

**Comment by keivanshahida** [comment]
- [x] Tapping on a person likes your song notification. Tapping on this notification brings you to the Feed, ideally scrolled to the correct post
- [x] Rethink where we want a "liked song" notification action to take you within the app (feed, posthistory).. For now it will take you straight to feed.
- [x] Clicking on "... is following you" notification should bring you to their profile

**Comment by keivanshahida** [comment]
- [x] Implement Instagram like banner AND red dot to show unread notifications.
