### ISSUE TITLE
History - Drag up bounce back

### ISSUE THREAD

**Issue by jonleenj** [cuappdev/icefishing#241]
On one's profile, even if there isn't anything more to see, when one tries to scroll, it should show a bit of black and then bounce back to current view. 

![img_9387](https://cloud.githubusercontent.com/assets/7338439/22531531/705e9f7a-e8af-11e6-8b5c-da1c0a95609f.PNG)

Also that grey area on the bottom should be black. Calendar container should fill the entire bottom. (Does this make sense...)

**Comment by dennisfedorko** [comment]
I was playing around with the bounce behavior and didn't like it, but we can play around with it. The gray bar is an easy fix

**Comment by dennisfedorko** [comment]
Fixed for the most part but without bounce, we can re-create the bounce as a separate issue if we decide to add that in.
