### ISSUE TITLE
Remove Follow Button from Followers and Following Views

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#26]
Bug introduced in #20 by @mrkbryn. Easy fix.
- [ ] Remove from Followers
- [ ] Remove from Following

**Comment by mrkbryn** [comment]
Isn't the follow button a part of the original feature? I thought the decision was to have the follow button in all types of user table views.

**Comment by say25** [comment]
Backend made this confusing. better fix is changing UI.
