### ISSUE TITLE
User posts same song twice in 24 hrs

### ISSUE THREAD

**Issue by ChenJesse** [cuappdev/icefishing#261]
![simulator screen shot feb 15 2017 6 44 51 pm](https://cloud.githubusercontent.com/assets/11747956/23000519/e4a79792-f3ae-11e6-972c-df8323b9dfe5.png)

Somehow Nic Pavao managed to post the same song twice, which should not be allowed. There is a current guard against that, in that you shouldn't be able to click the "Share" button if you've posted the song in the past 24 hrs

**Comment by loganallen** [comment]
^lol

**Comment by loganallen** [comment]
Maybe it wasn't EXACTLY the same song? Maybe one was like "- remastered". Cuz when you search a song multiple of seemingly the same song pop up

**Comment by ChenJesse** [comment]
Hmm, maybe, I'll just close this for now unless anybody sees the bug again then
