### ISSUE TITLE
Feed Cell Size Issue

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#28]
Size should be variable
![img_0051](https://cloud.githubusercontent.com/assets/7467062/7339342/55d4a380-ec39-11e4-9eb1-ec3727da1285.jpg)

**Comment by say25** [comment]
Size issue expected to be caused from sidebar size:
![img_0052](https://cloud.githubusercontent.com/assets/7467062/7362285/9c9dcbe2-ed34-11e4-94b6-22dde78e54ac.jpg)

**Comment by lucasderraugh** [comment]
Fixed with commit a43e721bfcc45ef83e3b9fd05a05deaa2e1a8740
