### ISSUE TITLE
Pinned Feed Cell Color Issue

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#29]
![ios simulator screen shot apr 26 2015 5 27 35 pm](https://cloud.githubusercontent.com/assets/7467062/7339355/9bace282-ec39-11e4-9b8f-ece97b5d7095.png)

**Comment by say25** [comment]
Hint: FeedViewController.xib is part of the problem.

**Comment by lucasderraugh** [comment]
Fixed with commit 017eec8391f76a6e44465a9bdf1caf9c8bf67b85
