### ISSUE TITLE
Phil Collins Bug

### ISSUE THREAD

**Issue by keivanshahida** [cuappdev/icefishing#295]
When I search for a song, the first entry shows up properly, but when I click on it, Phil Collins plays...

**Comment by keivanshahida** [comment]
Now every song I search for plays Phil Collins...

**Comment by Jma353** [comment]
Wtf is this

**Comment by dantheli** [comment]
It's literally cause it's hardcoded into the freaking app

**Comment by dantheli** [comment]
![image](https://user-images.githubusercontent.com/15382898/29697418-1d065b9c-891d-11e7-8ef8-51aafeb5ea37.png)

**Comment by dantheli** [comment]
Fixed with df729a9 on joe/api branch
