### ISSUE TITLE
Persistent Spotify Checkmarks

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#3]
Steps to replicate:
1. Open the App, Login in, Login to Spotify
2. Click the Plus button on a song (adding it to your songs on Spotify), it will turn into a check mark
3. Quit the app and close it from the background
4. Reopen the app and look at that song. The check mark will be a plus again. Songs already in your Songs list should be a check mark rather than a plus on load as well.

**Comment by lucasderraugh** [comment]
Merged in 9a05fc9
