### ISSUE TITLE
Connect Follow Button to DB

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#36]

**Comment by lucasderraugh** [comment]
Issues remain in terms of keeping stats on whether a user is being followed or not. The local counting doesn't check against if the user is currently being followed or not so the counts can get screwed if you unfollow someone you're already following for example. However, on the backend these values are recorded correctly regardless. For this reason I'm going to close this issue and if @say25 wants to open a new one regarding the local count he can.
