### ISSUE TITLE
Add Login with Spotify Screen and Functionality

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#43]
This issue encompasses the Spotify ViewController showing either: 
1. Logged in use, Spotify profile picture, ability to log out of Spotify and the ability to jump to Spotify.
2. The ability to log in to Spotify.

**Comment by say25** [comment]
Helpful links: https://github.com/spotify/ios-sdk, https://developer.spotify.com/web-api/add-tracks-to-playlist/, https://developer.spotify.com/web-api/create-playlist/

**Comment by eappel** [comment]
@lucasderraugh lets push a new vc when "spotify" is selected in the side-menu and add a simple spotify oauth button to it.  Once the user signs in, the spotify menu button should present a tableViewController of the user's playlists

**Comment by lucasderraugh** [comment]
@acheng96 Interesting to note that spotify/ios-sdk/issues/473 has the issue you ran into today. Sounds like this API is just overall a huge mess.

**Comment by eappel** [comment]
is the error in the network request or in the SPTTrack constructor?
