### ISSUE TITLE
Attach Handle Creation To DB

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#44]
1. Should not allow spaces, should only allow alphanumeric "ab...xyz12...90" characters and underscore "_"
2. Handles should be case-insensitive. 
Ex 1: "Steven" and "steven" are the same 
Ex 2: "StevEn" and "steven" are the same 
3. Field should start with '@' symbol
4. Ability to change handle.

**Comment by acheng96** [comment]
Fixed 3a5492c
