### ISSUE TITLE
Switch likes label with timestamp label on feed cells

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#46]
The number of likes should be above the heart, and the timestamp should be below the song label. The UI doesn't work well as is.

**Comment by say25** [comment]
I believe this is due to our "cell convention". We put followers count below the name. Not to the right of it. Also dates/times don't change a lot in length compared to count and could vary the amount of song title we can display which could look odd.

**Comment by dennisfedorko** [comment]
Things that are alike should be grouped together, hence like count should be near the heart icon, so you can see it go up when you like it. Right now the likes counter is essentially hidden. Nobody cares about the date posted, its already chronological, the number of likes is what people really care about. I don't see how this would change the UI much, label widths would stay the same since date posted and likes would just swap, they're both about the same length anyway.

**Comment by dennisfedorko** [comment]
see following twitter post for example, notice how date posted is grouped with name, and likes count is right next to the heart. My suggestion is to put the date posted under the song name where the likes counter currently is. <img width="591" alt="screen shot 2016-05-10 at 9 03 13 am" src="https://cloud.githubusercontent.com/assets/7183643/15147319/181c4018-168e-11e6-85e3-216cac0c8b45.png">
