### ISSUE TITLE
Profile "Post History" button should do something, or not be a button

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#51]
This should either open up a tableview with all the songs you've ever posted (maybe even along with likes for those posts), or it should not exist, and the timeline could be bigger.

**Comment by lucasderraugh** [comment]
It brings you back to the top if I remember the implementation correctly. Kinda a useless button in general.

**Comment by dennisfedorko** [comment]
This should be the "Full History" button
