### ISSUE TITLE
Feed item plus button

### ISSUE THREAD

**Issue by eappel** [cuappdev/icefishing#52]
Tapping the "+" button on a song anywhere in the app should add that song to the user's "Songs" playlist in Spotify.  Note: this is the exact same functionality of tapping a "+" in the spotify app.  

Bonus points: Tapping and holding should present a modal tableView of the user's spotify playlists and allow him/her to add the song to a specific playlist.  

Obviously, these should only be enabled if the user is signed in to spotify

**Comment by lucasderraugh** [comment]
Closed in f1db018
