### ISSUE TITLE
Create an about tab

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#54]
Have a tab in the hamburger menu with info about the appDev team with links to our site/github/twitter, etc. and the names of all the people who contributed to the project on our team.

**Comment by tz226** [comment]
doing a quick mock up. double checking on the info to place on it: 
github https://github.com/cuappdev/
twitter https://twitter.com/cornellappdev/ 
website http://www.cuappdev.org/

What info do you want? I'll just place loreum ipsum for now...And is there a list of team members anywhere?

**Comment by tz226** [comment]
![about page](https://cloud.githubusercontent.com/assets/7338439/18821487/88011446-8374-11e6-8d7e-fa6bc8ed62bc.png)
