### ISSUE TITLE
Update Profile picture

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#55]
allow users to change their profile picture to something in their library using uiimagepicker

**Comment by lucasderraugh** [comment]
More of a backend thing (needing to host images). We currently just link against their profile picture.

**Comment by say25** [comment]
I don't think this is a big priority. Also I believe some of the sign up with Facebook services for chatting on articles doesn't allow profile picture changing. This issue goes along with #31.

**Comment by dennisfedorko** [comment]
How isn't the backend integrated with this? How are we currently getting the photo for the people you're following and/or the profile picture on the feed? That has to be stored somewhere on backend doesn't it?

**Comment by say25** [comment]
As Lucas said. It's stored by grabbing Facebook profile picture based on FacebookId on User. To our knowledge.

**Comment by dennisfedorko** [comment]
so then its stored in the backend under some field user.photo, to upload a new photo should be as simple as a post request. its just something to consider, since your profile picture shows up everywhere in our app.

**Comment by say25** [comment]
I don't think you quiet understand. To our knowledge, the user object has a Facebook id. Wheneverer we load users we say hey what is that users Facebook ID and go to www.facebook.com/{userid}/profilepicture/small and retrieve that image from Facebook. So it's not really storing the image so much as a "reference" to it.

**Comment by dennisfedorko** [comment]
So instead of just storing a 50x50px image, we're storing a url to retrieve the image, which means it takes longer to fetch the photo, and we can't update it. Why not just store the photo instead of the reference, it wouldn't take up that much space if we don't let people expand photos.
