### ISSUE TITLE
Open Facebook app to login

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#56]
If the user has the Facebook app on their phone, use it to sign in instead of a web view.

**Comment by lucasderraugh** [comment]
This is changed by design in iOS 9: https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by dennisfedorko** [comment]
this is a huge pain for people who don't use Facebook on mobile and have to login
