### ISSUE TITLE
Post history should only show songs from that day

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#57]
This might just be my opinion, but the post history should only show me the songs I posted on that day instead of my entire history.

**Comment by lucasderraugh** [comment]
I think that would be a pain to find a song you remember from about 2 weeks back but have to select specific sections until you find the right one.

**Comment by dennisfedorko** [comment]
thats why there should be a separate "full history" button which shows you all songs in chronological order. Right now that's what I assume the "POST HISTORY" button on profile is for.
