### ISSUE TITLE
Fix Spotify playlist integration

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#59]
Spotify playlist should sync when you refresh your feed. Right now it's not working for me, and for some reason I have two ice fishing playlists.

**Comment by celinebrass** [comment]
For the two playlists, did you ever register twice with Spotify on our app in the midst of the db dropping/creation stuff?  There could definitely be a bug causing two playlists but figured I would check that first.  

Also, why would syncing on refresh be better than syncing as people post?

Will definitely check out the two playlists though.

**Comment by dennisfedorko** [comment]
It's probably due to the DB drop, but it should check to make sure a playlist doesn't exist before it makes a new one.

I'm worried that when someone follows a new person, that they won't get the songs that person posted earlier in the day on their playlist. Loading playlist on pull to refresh might not be the best solution.

**Comment by dennisfedorko** [comment]
Doesn't explain why my playlist isn't being updated though
