### ISSUE TITLE
Add welcome screens to introduce user to Tempo and guide them through setting up spotify

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#70]
Facebook Login -> Spotify Setup -> Explanation of how to use the app -> Add Friends -> Enter

For add friends, we should use the suggestion endpoint Ilan built to suggest people for the user to follow before they get to an empty feed and encounter the cold-start issue. Maybe even have them auto-follow a certain set of users who consistently post

**Comment by say25** [comment]
#6 was a duplicate
