### ISSUE TITLE
People Searching a User with No Followers Give CurrentUsers' Followers and Following

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#88]
The user with handle "@fox" has no followers.
Issues also arise when current user has no followers. 
Issues stems from ProfileViewController:
// Accounts for case where we select user from feed image
	if user.followersCount == 0 {
		API.sharedAPI.fetchUser(user.id) {
		self.user = $0
		self.followingButton.setTitle("\($0.followingCount) Following", forState: .Normal)
	        self.followersButton.setTitle("\($0.followersCount) Followers", forState: .Normal)
	}
}

**Comment by lucasderraugh** [comment]
`/users/userID` Always gives back the current user no matter the what the `userID` happens to be. @ifilonenko can you look into this?

**Comment by say25** [comment]
Closed with ice fishing-web commit
